version: "4.5"
services:
  web-shiro:
    # build: ./web-shiro
    image: ctfarchives/puff-pastry-web-shiro:latest
    restart: always
    volumes:
      - ./flag/web-shiro.txt:/flag.txt:ro
    ports:
      - "8080:8080"
    networks:
      - entry

  web-thinkphp:
    build: ./web-thinkphp
    # image: ctfarchives/puff-pastry-web-thinkphp:latest
    restart: always
    volumes:
      - ./flag/web-thinkphp.txt:/flag.txt:ro
    networks:
      - entry
      - sub-1

  db-redis:
    build: ./db-redis
    restart: always
    volumes:
      - ./flag/db-redis.txt:/flag.txt:ro
    networks:
      - sub-1

  web-phpmyadmin:
    build: ./web-phpmyadmin
    restart: always
    volumes:
      - ./flag/web-phpmyadmin.txt:/flag.txt:ro
      - ./flag/db-mysql.sql:/var/db.sql:ro
    environment:
      PMA_HOST: 127.0.0.1
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    networks:
      - sub-1
      - sub-2

  web-struts2:
    build: ./web-struts2
    restart: always
    volumes:
      - ./flag/web-struts2.txt:/flag.txt:ro
    networks:
      - sub-2

  db-postgresql:
    build: ./db-postgresql
    restart: always
    environment:
      - "POSTGRES_PASSWORD=password"
    volumes:
      - ./flag/db-postgresql.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    networks:
      - sub-2

networks:
  entry:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24

  sub-1:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 10.85.101.0/24

  sub-2:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.56.102.0/24
