version: "2"
services:
  web-nginx:
    image: nginx:latest
    ports:
      - 8081:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - phpmyadmin_data:/var/www/html/:ro
    networks:
      - phpmyadmin

  web-phpmyadmin:
    build: ../web-phpmyadmin
    restart: always
    volumes:
      - ../flag/web-phpmyadmin.txt:/flag.txt:ro
      - ./zzz-docker.conf:/usr/local/etc/php-fpm.d/zzz-docker.conf
      - phpmyadmin_data:/var/www/html
    environment:
      PMA_HOST: db-mariadb
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    depends_on:
      - db-mariadb
    networks:
      - phpmyadmin

  db-mariadb:
    build: ../db-mysql
    container_name: db-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: app_db
    volumes:
      - ../flag/db-mysql.sql:/docker-entrypoint-initdb.d/schema.sql:ro
      - phpmyadmin_data:/var/www/html
    networks:
      - phpmyadmin

networks:
  phpmyadmin:

volumes:
  phpmyadmin_data:
